# Generated by Django 3.2.9 on 2021-12-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tweet_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
